### ISSUE TITLE
The issues about cmake build type 

### ISSUE THREAD

**Issue by TrackingBird** [VLOGroup/imageutilities#11]
Dear Sir, sorry to bother you. 
I am confused about the cmake_build_type after make. My CMAKE_BUILD_TYPE: RelWithDebInfo, while others are Release. Hope for your help, thanks very much. Here is my make results:
sudo make -j4
COMPILER FLAGS:
-- **CMAKE_BUILD_TYPE: RelWithDebInfo**
-- BUILD_SHARED_LIBS: ON
-- CMAKE_C_FLAGS= 
-- CMAKE_CXX_FLAGS = -std=c++11 -fPIC -fmax-errors=3 -fpermissive -ggdb -Wunused-result -Wno-unused-variable -Wno-unused-value -Wno-unused-but-set-variable -Wdisabled-optimization -Wdiv-by-zero -Wc++11-compat -Wno-float-equal -fopenmp -O2 -DPARALLEL -ffast-math -DNDEBUG
-- CMAKE_CXX_FLAGS_RELEASE = -O3 -DNDEBUG
-- CUDA_NVCC_FLAGS= -arch=sm_30;-expt-extended-lambda;-ftemplate-backtrace-limit=2;-lineinfo;-std=c++11;-Xcompiler=-Wno-sign-compare;-O2;-keep;-src-in-ptx;-DNDEBUG;-Xptxas=-warn-lmem-usage;-Xptxas=-warn-spills
-- CUDA_PROPAGATE_HOST_FLAGS= OFF
-- COMPILE_DEFINITIONS = 
[+] ImageUtilities include IO module
Found OpenCV Version: 3.1
Enabling fixes for OpenCV >= 3
  [-] build io module without Flycapture2/Pointgrey support
  [+] build io module with OpenEXR support
include dirs: /usr/include/usr/include/OpenEXR
[+] ImageUtilities include GUI module
[+] ImageUtilities include Math module
[+] ImageUtilities include ndarray module
[-] do not build static library
additional iuio libs: /usr/lib/x86_64-linux-gnu/libHalf.so;/usr/lib/x86_64-linux-gnu/libIex.so;/usr/lib/x86_64-linux-gnu/libIlmImf.so;/usr/lib/x86_64-linux-gnu/libIlmThread.so;/usr/lib/x86_64-linux-gnu/libImath.so
opencv_coreopencv_highguiopencv_videostabopencv_videoioopencv_coreopencv_imgcodecsopencv_imgprocopencv_highgui
install: /usr/local
-- Configuring done
-- Generating done
-- Build files have been written to: /home/jennifer/cnn-crf-stereo-master/dependencies/imageutilities/build

**Comment by pknoebelreiter** [comment]
We had some troubles with CMAKE_BUILD_TYPE=Release at some point. RelWithDebInfo always worked for us. 

Did you set IMAGE_UTILITIES_ROOT correctly (as specified in the Readme)? Because you are going to install the libs to /usr/local which indicates the variable is not set correctly. Our FindImageUtilities script will only work if this variable is not set correctly.

The rest of the configuration looks good.

**Comment by TrackingBird** [comment]
Yes, you are right. I finished this issue by install the libs to imageImageUtilities file.
