### ISSUE TITLE
iuio module not installing

### ISSUE THREAD

**Issue by nelkabosal** [VLOGroup/imageutilities#12]
I'm trying to install imageutitlies in order to support installing [dvs-reconstruction](https://github.com/VLOGroup/dvs-reconstruction). The error appears to be in the imageutilities install, where it is not installing the iuio module, specifically: 
```
    CMake Error at /home/kjnelson/dvs-reconstruction/imageutilities/ImageUtilitiesConfig.cmake:137 (message):
    iuio marked as required but not found
```

I've attached all of my install commands and complete output. I did it all within an Anaconda virtual environment where I'd previously installed OpenCV, and the only requirement I can see for iuio is for OpenCV 2.4 or 3.x installed. I have OpenCV 3.4.0 installed. Any assistance to troubleshoot would be appreciated. 
[installOutputwithErrors.pdf](https://github.com/VLOGroup/imageutilities/files/2024010/installOutputwithErrors.pdf)

**Comment by nelkabosal** [comment]
I asked around for advice and got some help. I removed QUIET from this line

`find_package( OpenCV COMPONENTS opencv_core opencv_highgui opencv_videostab)`

and got this output:

```
CMake Warning at /home/kjnelson/opencv-3.1.0/cmake/OpenCVConfig.cmake:166 (message):
  Found OpenCV Windows Pack but it has no binaries compatible with your
  configuration.

  You should manually point CMake variable OpenCV_DIR to your build of OpenCV
  library.
Call Stack (most recent call first):
  src/CMakeLists.txt:97 (find_package)


CMake Warning at src/CMakeLists.txt:97 (find_package):
  Found package configuration file:

    /home/kjnelson/opencv-3.1.0/cmake/OpenCVConfig.cmake

  but it set OpenCV_FOUND to FALSE so package "OpenCV" is considered to be
  NOT FOUND.

```

So, it ought to be looking in `/usr/local/share/OpenCV` for my build of OpenCV library. Where should I be looking to manually point CMake variable OpenCV_DIR to my build of OpenCV library?

**Comment by reini1305** [comment]
How did you install OpenCV? It says "Windows Pack". Which operating system are you running this on? I recommend compiling OpenCV yourself or using Ubuntu 16.04 which has the right OpenCV version installable via the package manager.

**Comment by nelkabosal** [comment]
So, just in case anyone else has the same issue as me, the solution that resolved this issue for me was to open `imageutilities/ImageUtilitiesConfig.cmake` and replace `find_package( OpenCV REQUIRED COMPONENTS opencv_videoio opencv_core opencv_imgcodecs opencv_imgproc opencv_highgui)` with `find_package( OpenCV REQUIRED videoio core imgcodecs imgproc highgui)`. 

And then I opened `imageutilities/src/CmakeLists.txt` and replaced `find_package( OpenCV QUIET COMPONENTS opencv_core opencv_highgui opencv_videostab)` with `find_package( OpenCV REQUIRED core highgui videostab)` and replaced `find_package( OpenCV QUIET COMPONENTS opencv_videoio opencv_core opencv_imgcodecs opencv_imgproc opencv_highgui)` with `find_package( OpenCV REQUIRED videoio core imgcodecs imgproc highgui)`

**Comment by satabios** [comment]
> So, just in case anyone else has the same issue as me, the solution that resolved this issue for me was to open `imageutilities/ImageUtilitiesConfig.cmake` and replace `find_package( OpenCV REQUIRED COMPONENTS opencv_videoio opencv_core opencv_imgcodecs opencv_imgproc opencv_highgui)` with `find_package( OpenCV REQUIRED videoio core imgcodecs imgproc highgui)`.
> 
> And then I opened `imageutilities/src/CmakeLists.txt` and replaced `find_package( OpenCV QUIET COMPONENTS opencv_core opencv_highgui opencv_videostab)` with `find_package( OpenCV REQUIRED core highgui videostab)` and replaced `find_package( OpenCV QUIET COMPONENTS opencv_videoio opencv_core opencv_imgcodecs opencv_imgproc opencv_highgui)` with `find_package( OpenCV REQUIRED videoio core imgcodecs imgproc highgui)`

I made the changes quoted, I'm still encountering the same error. I'm attaching logs for reference.
[CMakeOutput.log](https://github.com/VLOGroup/imageutilities/files/5349519/CMakeOutput.log) 

[CMakeError.log](https://github.com/VLOGroup/imageutilities/files/5349518/CMakeError.log)
