### ISSUE TITLE
iucore marked as required but not found

### ISSUE THREAD

**Issue by satabios** [VLOGroup/imageutilities#14]
`cmake  ../src ` results in

`-- The C compiler identification is GNU 4.9.4
-- The CXX compiler identification is GNU 4.9.4
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Found CUDA: /usr/local/cuda-9.2 (found suitable version "9.2", minimum required is "5.0") 
-- Imageutilities requested components: iucore;iuio;iugui;iumath
CMake Error at /mnt/62E2AC72E2AC4BDB/DAVIS/dvs-reconstruction/imageutilities/ImageUtilitiesConfig.cmake:137 (message):
  iucore marked as required but not found
Call Stack (most recent call first):
  CMakeLists.txt:25 (find_package)`

-- Configuring incomplete, errors occurred!
See also "/mnt/62E2AC72E2AC4BDB/DAVIS/dvs-reconstruction/build/CMakeFiles/CMakeOutput.log".
See also "/mnt/62E2AC72E2AC4BDB/DAVIS/dvs-reconstruction/build/CMakeFiles/CMakeError.log".

 I'm attaching the logs for reference.
[CMakeError.log](https://github.com/VLOGroup/imageutilities/files/5352882/CMakeError.log)
[CMakeOutput.log](https://github.com/VLOGroup/imageutilities/files/5352883/CMakeOutput.log)

**Comment by reini1305** [comment]
Did you set the IMAGEUTILITITES_ROOT env like mentioned in the Readme? :)

**Comment by satabios** [comment]
> Did you set the IMAGEUTILITITES_ROOT env like mentioned in the Readme? :)

Yes, I've added the below lines to my .bashrc 
export MATLAB_ROOT=/usr/local/MATLAB/R2019b
export CUDA_SDK_ROOT_DIR=/usr/local/cuda-9.2/samples/common/inc
export IMAGEUTILITIES_ROOT=/mnt/62E2AC72E2AC4BDB/DAVIS/dvs-reconstruction/image$
export COMPUTE_CAPABILITY=9.2
#export IMAGEUTILITIES_ROOT=/media/14tb/sathya/dvs-reconstruction/imageutilitie$
#alias matlab='LD_PRELOAD=/usr/loib/x86_64-linux-gnu/libstdc++.so.6.0.22 /usr/l$
export CPATH=$CPATH:/usr/local/cuda-9.2/samples/common/inc
export LD_LIBRARY_PATH=/usr/local/lib/:$LD_LIBRARY_PATH

**Comment by reini1305** [comment]
> export IMAGEUTILITIES_ROOT=/mnt/62E2AC72E2AC4BDB/DAVIS/dvs-reconstruction/image

Is it really in this directory or is that a typo?

**Comment by vigneshkgith** [comment]
> `cmake ../src ` results in
> 
> `-- The C compiler identification is GNU 4.9.4 -- The CXX compiler identification is GNU 4.9.4 -- Check for working C compiler: /usr/bin/cc -- Check for working C compiler: /usr/bin/cc -- works -- Detecting C compiler ABI info -- Detecting C compiler ABI info - done -- Detecting C compile features -- Detecting C compile features - done -- Check for working CXX compiler: /usr/bin/c++ -- Check for working CXX compiler: /usr/bin/c++ -- works -- Detecting CXX compiler ABI info -- Detecting CXX compiler ABI info - done -- Detecting CXX compile features -- Detecting CXX compile features - done -- Looking for pthread.h -- Looking for pthread.h - found -- Looking for pthread_create -- Looking for pthread_create - not found -- Looking for pthread_create in pthreads -- Looking for pthread_create in pthreads - not found -- Looking for pthread_create in pthread -- Looking for pthread_create in pthread - found -- Found Threads: TRUE -- Found CUDA: /usr/local/cuda-9.2 (found suitable version "9.2", minimum required is "5.0") -- Imageutilities requested components: iucore;iuio;iugui;iumath CMake Error at /mnt/62E2AC72E2AC4BDB/DAVIS/dvs-reconstruction/imageutilities/ImageUtilitiesConfig.cmake:137 (message): iucore marked as required but not found Call Stack (most recent call first): CMakeLists.txt:25 (find_package)`
> 
> -- Configuring incomplete, errors occurred!
> See also "/mnt/62E2AC72E2AC4BDB/DAVIS/dvs-reconstruction/build/CMakeFiles/CMakeOutput.log".
> See also "/mnt/62E2AC72E2AC4BDB/DAVIS/dvs-reconstruction/build/CMakeFiles/CMakeError.log".
> 
> I'm attaching the logs for reference.
> [CMakeError.log](https://github.com/VLOGroup/imageutilities/files/5352882/CMakeError.log)
> [CMakeOutput.log](https://github.com/VLOGroup/imageutilities/files/5352883/CMakeOutput.log)

Hi  I'm getting this same error while using cmake ../src, even after setting all environment variables as required

**Comment by satabios** [comment]
> > export IMAGEUTILITIES_ROOT=/mnt/62E2AC72E2AC4BDB/DAVIS/dvs-reconstruction/image
> 
> Is it really in this directory or is that a typo?

Sorry it was a typo,

the actualy path was set to : export IMAGEUTILITIES_ROOT=/mnt/62E2AC72E2AC4BDB/DAVIS/dvs-reconstruction/imageutilities

**Comment by reini1305** [comment]
Did you also install the imageutilities in that directory? You can tell if there is a lib/ folder in the imagutilities folder.

**Comment by vigneshkgith** [comment]
For me , I cloned dvs-reconstruction recursively , and built the image utilities as its github page said there itself ...
There is a lib/ folder in the imageutilities folder for me ... Is it not right to do it that way? Please guide how to proceed :)..and please tell if any details you need regarding installation directory etc
> Did you also install the imageutilities in that directory? You can tell if there is a lib/ folder in the imagutilities folder.

**Comment by reini1305** [comment]
Well, that should work after all. IMAGEUTILITIES_ROOT should simply point to the install directory.

**Comment by satabios** [comment]
> ll the imageutilities in that directory? You can tell if there is a lib/ folder in the imagutilities folder.

Yes I can find the lib folder and I've also set the IMAGEUTILITIES_ROOT path.

**Comment by vigneshkgith** [comment]
I installed OpenCV 3.4.2 from source using this link https://medium.com/@rabbi.cse.sust.bd/how-to-install-opencv3-for-python3-in-ubuntu-18-04-lts-4f369f5c514d and changed the openCV_DIR variable to point to opencv_src/opencv_release/share/OpenCV ... This solved the issue... Thanks :) .. Probably the issue was with opencv version 4
