### ISSUE TITLE
cannot build with latest codes

### ISSUE THREAD

**Issue by raymond00000** [VLOGroup/imageutilities#2]
I downloaded the latest code by git clone command. Then i followed the step to make. My log:

[ 26%] Built target ndarray
[ 27%] Building NVCC (Device) object src/CMakeFiles/iucore.dir/iucore/iucore_generated_remap.cu.o
In file included from /home/raymond/dvs/imageutilities/src/common/bsplinetexture_kernels.cuh:3:0,
                 from /home/raymond/dvs/imageutilities/src/iucore/remap.cu:6:
/home/raymond/dvs/imageutilities/src/common/vectormath_kernels.cuh:3:25: fatal error: helper_math.h: No such file or directory
compilation terminated.
CMake Error at iucore_generated_remap.cu.o.cmake:203 (message):
  Error generating
  /home/raymond/dvs/imageutilities/build/src/CMakeFiles/iucore.dir/iucore/./iucore_generated_remap.cu.o

src/CMakeFiles/iucore.dir/build.make:654: recipe for target 'src/CMakeFiles/iucore.dir/iucore/iucore_generated_remap.cu.o' failed
make[2]: *** [src/CMakeFiles/iucore.dir/iucore/iucore_generated_remap.cu.o] Error 1
CMakeFiles/Makefile2:175: recipe for target 'src/CMakeFiles/iucore.dir/all' failed
make[1]: *** [src/CMakeFiles/iucore.dir/all] Error 2
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2

"helper_math.h" was removed in previous commit, but it is still included in some code file??
commented out this include line leads to other error message. 

Thanks.

**Comment by reini1305** [comment]
`helper_math.h` is from the CUDA toolkit, we had to remove it because of possible copyright issues. This means, it is now taken from the installed CUDA toolkit. Make sure that `CUDA_SDK_ROOT_DIR` is set in CMake. On my linux system it points to `/usr/local/cuda/samples`.

**Comment by raymond00000** [comment]
thanks, right!
I can build now.

Can you explain what below line mean?

Set up environment variable COMPUTE_CAPABILITY with the CC of your CUDA-enabled GPU

Thank a lot!

**Comment by reini1305** [comment]
Right, we should probably document that better :)
Depending on your graphics card, you can set the compute capability: https://en.wikipedia.org/wiki/CUDA#GPUs_supported

If you don't specify it, it will default to 3.5 which is the minimum necessary.

**Comment by reini1305** [comment]
Can we close this issue?

**Comment by raymond00000** [comment]
thank a lot!

**Comment by Lvhhhh** [comment]
i have set ' 'export CUDA_SDK_ROOT_DIR=$CUDA_SDK_ROOT_DIR:/usr/local/cuda-8.0/samples'' in '~/.bashrc' and then 'source ~/.bashrc '
 but i still have this problem~/.
