### ISSUE TITLE
does not support Jetson tk1

### ISSUE THREAD

**Issue by raymond00000** [VLOGroup/imageutilities#3]
The tools does not support Jetson tk1. I know Jetson CC is just 3.2, the mini req is 3.5.
What a pity. 

ubuntu@tegra-ubuntu:~/dvs/imageutilities/build$ make
[  2%] Building NVCC (Device) object src/CMakeFiles/iucore.dir/iucore/iucore_generated_remap.cu.o
/home/ubuntu/dvs/imageutilities/src/iucore/vector.h(516): error: nontype "iu::SizeBase<Ndim>::SizeBase [with Ndim=Ndim]" is not a template

/home/ubuntu/dvs/imageutilities/src/iucore/vector.h(529): error: nontype "iu::SizeBase<Ndim>::SizeBase [with Ndim=Ndim]" is not a template

/home/ubuntu/dvs/imageutilities/src/iucore/vector.h(350): error: nontype "iu::VectorBase<PixelType, Ndim>::VectorBase [with PixelType=unsigned int, Ndim=Ndim]" is not a template

/home/ubuntu/dvs/imageutilities/src/iucore/vector.h(511): error: nontype "iu::SizeBase<Ndim>::SizeBase [with Ndim=Ndim]" is not a template
          detected during instantiation of "iu::Size<Ndim> iu::LinearMemory<Ndim>::size() const [with Ndim=1U]" 
/home/ubuntu/dvs/imageutilities/src/iucore/memorydefs.h(345): here

4 errors detected in the compilation of "/tmp/tmpxft_00000c4b_00000000-6_remap.cpp1.ii".
CMake Error at iucore_generated_remap.cu.o.Release.cmake:278 (message):
  Error generating file
  /home/ubuntu/dvs/imageutilities/build/src/CMakeFiles/iucore.dir/iucore/./iucore_generated_remap.cu.o

make[2]: *** [src/CMakeFiles/iucore.dir/iucore/iucore_generated_remap.cu.o] Error 1
make[1]: *** [src/CMakeFiles/iucore.dir/all] Error 2
make: *** [all] Error 2
ubuntu@tegra-ubuntu:~/dvs/imageutilities/build$

**Comment by reini1305** [comment]
We do not have a TK1 for testing. Theoretically it should be possible. 3.5 was set as minimum since "cuda texture objects" have been introduced there (but they could also be in 3.2). Which compiler are you using? `nvcc --version` and `gcc --version` I think...

**Comment by raymond00000** [comment]
My board is at another office today. I can run the nvcc and gcc tmr and please let me confirm you tmr, 

But for TK1, it only supports cuda 6.5.

    nvcc: NVIDIA (R) Cuda compiler driver
    Copyright (c) 2005-2014 NVIDIA Corporation
    Built on Fri_Dec_12_11:12:07_CST_2014
    Cuda compilation tools, release 6.5, V6.5.35


The newest directly supported L4T is R21.4, based on Ubuntu 14.04.3 LTS (L4T basically adds hardware accelerated access). The most updated gcc directly installed from standard repositories is "gcc (Ubuntu/Linaro 4.8.4-2ubuntu1~14.04) 4.8.4".

https://devtalk.nvidia.com/default/topic/867751/jetson-tk1/updating-linux-on-jetson-tk1-cc-version-bump-/

Many thanks for having a look.

**Comment by reini1305** [comment]
OK, in this case the problem is that we require C++-11 and this is only supported in nvcc since 7.0. I will update the documentation accordingly!
