### ISSUE TITLE
Compiling problem

### ISSUE THREAD

**Issue by Thanh-Binh** [VLOGroup/imageutilities#6]
by building, there is an error like
/home/test/dvs-panotracking/imageutilities/src/common/vectormath_kernels.cuh:3:25: fatal error: helper_math.h: No such file or directory
compilation terminated.

Where can I find this header?

**Comment by reini1305** [comment]
Did you follow the build instructions and set the env variable `CUDA_SDK_ROOT_DIR`? Which operating system, CUDA version and graphics card are you using?

**Comment by Thanh-Binh** [comment]
it solved after setting this variable
CUDA_SDK_ROOT_DIR=/usr/local/cuda-8.0/samples/

**Comment by reini1305** [comment]
Cool! Then let's get you other problem fixed next :)

**Comment by Thanh-Binh** [comment]
how does this environment variable "COMPUTE_CAPABILITY with the CC of your CUDA-enabled GPU" look like?

**Comment by reini1305** [comment]
For instance "3.5" and so on. If you don't set it, it will default to the minimum compute capability necessary.

**Comment by Thanh-Binh** [comment]
That mean version of Cc. I use gcc 4.8 and gcc 5.should i write "4.8"?

**Comment by reini1305** [comment]
CC is for Compute Capability. Not setting it is perfectly fine.

**Comment by Thanh-Binh** [comment]
Sorry for my missunderstanding!how can i findout this info for cc in my gpu?

**Comment by reini1305** [comment]
You can find them here: https://en.wikipedia.org/wiki/CUDA

I'll add that link to the readme.

**Comment by Thanh-Binh** [comment]
Yes i see it, but how important is this parameter? What is happened by a false estimation of this value at the building phase?

**Comment by reini1305** [comment]
Not that important in practice

**Comment by Lvhhhh** [comment]
how to "Set up environment variable COMPUTE_CAPABILITY with the CC of your CUDA-enabled GPU"?
because it is a number not like the path as i can set up them on "~/.bashrc"
thank u for your help!

**Comment by pknoebelreiter** [comment]
This is how I have set it in my .bashrc: `export COMPUTE_CAPABILITY=3.5`

**Comment by Lvhhhh** [comment]
i have set ' 'export CUDA_SDK_ROOT_DIR=$CUDA_SDK_ROOT_DIR:/usr/local/cuda-8.0/samples'' in '~/.bashrc' and then 'source /.bashrc '
but i still cannot find the help_math.h
