### ISSUE TITLE
iumat complie issue

### ISSUE THREAD

**Issue by trminh89** [VLOGroup/imageutilities#7]
Hi, I try to build the project, but got the following error. I did set the environment paths as in the README but no luck. Any suggestions?

Thanks a lot!

```
[  1%] Building NVCC (Device) object src/CMakeFiles/iumath.dir/iumath_generated_iumath.cu.o
Scanning dependencies of target iumath
[  3%] Linking CXX shared library libiumath.so
[  3%] Built target iumath
[  5%] Building NVCC (Device) object src/ndarray/CMakeFiles/ndarray.dir/ndarray_generated_test_iterator.cu.o
nvcc fatal   : Unknown option 'expt-extended-lambda'
CMake Error at ndarray_generated_test_iterator.cu.o.Release.cmake:218 (message):
  Error generating
  /home/imageutilities/build/src/ndarray/CMakeFiles/ndarray.dir/././ndarray_generated_test_iterator.cu.o


make[2]: *** [src/ndarray/CMakeFiles/ndarray.dir/ndarray_generated_test_iterator.cu.o] Error 1
make[1]: *** [src/ndarray/CMakeFiles/ndarray.dir/all] Error 2
make: *** [all] Error 2

```

**Comment by pknoebelreiter** [comment]
Hi! Which operating system are you using? Can you provide the output of CMake?

**Comment by trminh89** [comment]
Hi, thanks for the quick reply!
I'm using Ubuntu 14.04. I fixed this problem by upgrading to CUDA 8.0

It seem the option **expt-extended-lambda** only avaliable in CUDA >= 7.5. When I build with CUDA 7 it shows this error. Perhaps we should update the requirements for CUDA.

I'm trying to build with the GUI support (need QT5). My system has both QT4 and QT5, but it uses QT4 by default. How should I set the values of **Qt5Core_DIR**, **Qt5OpenGL_DIR** and **QT5Widgets_DIR**. Can you paste it from your system?

**Comment by pknoebelreiter** [comment]
Hi, you are right, expt-extended-lambda was introduced in CUDA 7.5 (https://devblogs.nvidia.com/parallelforall/new-features-cuda-7-5/). I will update the readme. 

Regarding QT5: I executed `ccmake ..` in my build folder. On my system (Ubuntu 16.04), the variables are set as follows:

```
 Qt5Core_DIR                      /usr/lib/x86_64-linux-gnu/cmake/Qt5Core                                                                                                                                                                   
 Qt5Gui_DIR                       /usr/lib/x86_64-linux-gnu/cmake/Qt5Gui                                                                                                                                                                    
 Qt5OpenGL_DIR                    /usr/lib/x86_64-linux-gnu/cmake/Qt5OpenGL                                                                                                                                                                 
 Qt5Widgets_DIR                   /usr/lib/x86_64-linux-gnu/cmake/Qt5Widgets  
```
Make sure you adapt the paths for your system.

**Comment by trminh89** [comment]
Thanks! It's all ok now!
