### ISSUE TITLE
I can't build dvs-reconstruction

### ISSUE THREAD

**Issue by immonomono** [VLOGroup/imageutilities#9]
I have problem when I try to build dvs-reconstruction becasue of following build error. 

ImageUtilities build was successful and I already set the 'IMAGEUTILITIES_ROOT'

Here is the build error

COMPILER FLAGS:
-- CMAKE_BUILD_TYPE: Release
-- BUILD_SHARED_LIBS: ON
-- CMAKE_C_FLAGS=  -fopenmp
-- CMAKE_CXX_FLAGS = -fopenmp -std=c++11 -fPIC -fmax-errors=3 -fpermissive -ggdb -Wunused-result -Wno-unused-variable -Wno-unused-value -Wno-unused-but-set-variable -Wdisabled-optimization -Wdiv-by-zero -Wc++11-compat -Wno-float-equal -O2 -DPARALLEL -ffast-math -DNDEBUG
-- CMAKE_CXX_FLAGS_RELEASE = -O3 -DNDEBUG
-- CUDA_NVCC_FLAGS= -arch=sm_30;-expt-extended-lambda;-ftemplate-backtrace-limit=2;-lineinfo;-std=c++11;-Xcompiler=-Wno-sign-compare;-O2;-keep;-src-in-ptx;-DNDEBUG;-Xptxas=-warn-lmem-usage;-Xptxas=-warn-spills
-- CUDA_PROPAGATE_HOST_FLAGS= OFF
-- COMPILE_DEFINITIONS =
-- Imageutilities requested components: iucore;iuio;iugui;iumath
**CMake Error at /home/mono/dev/imageutilities/ImageUtilitiesConfig.cmake:136 (message):
  iucore marked as required but not found**
Call Stack (most recent call first):
  CMakeLists.txt:25 (find_package)

-- Configuring incomplete, errors occurred!
See also "/home/mono/dev/dvs-reconstruction/build/CMakeFiles/CMakeOutput.log".
See also "/home/mono/dev/dvs-reconstruction/build/CMakeFiles/CMakeError.log".

**Comment by reini1305** [comment]
Did you also install the image utilities?

**Comment by reini1305** [comment]
Is this issue resolved?

**Comment by immonomono** [comment]
Do you mean 'make install'? Yes, I did

**Comment by reini1305** [comment]
Where did the iu install themselves? I would recommend to install them into the source (by changing the install_prefix in CMake to the directory where you unpacked the image utilities).

**Comment by immonomono** [comment]
It was solved when I install it in imageutilities directory. Thanks!

**Comment by satabios** [comment]
> It was solved when I install it in imageutilities directory. Thanks!

Can you brief on this?
I tried the above quoted techniques. Still I'm facing the same error. I'm attaching the logs for reference.
[CMakeError.log](https://github.com/VLOGroup/imageutilities/files/5349626/CMakeError.log)
[CMakeOutput.log](https://github.com/VLOGroup/imageutilities/files/5349627/CMakeOutput.log)

**Comment by vigneshkgith** [comment]
@satabios  Did you find a way out ? I am facing the same error while installing dvs-reconstruction.. Thanks

**Comment by reini1305** [comment]
@satabios  @vigneshkgith I have never seen such CMake errors before. Does it even get to compiling dvs-reconstruction?
